// This file is generated by convex-typegen. Do not modify directly.
// You can find more information about convex-typegen at https://github.com/JamalLyons/convex-typegen

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use serde::{Serialize, Deserialize};

#[derive(Debug, Clone)]
pub struct MessagesTable {
    pub author: String,
    pub body: String,
    pub timestamp: f64,
}

